# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
name: hoc-badge
'on':
  push:
    branches:
      - main
      - master
permissions:
  contents: read
concurrency:
  group: hoc-badge-${{ github.ref }}
  cancel-in-progress: true
jobs:
  hoc-badge:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Build a HOC badge
        uses: MikhailEpatko/hits-of-code-badge@da9d30c03970a5af529f69a1eaa3e35f3a65bd78
        with:
          output_dir: gh-pages
          filename: hoc-badge.svg
      - name: Release it into gh-pages
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8
        with:
          branch: gh-pages
          folder: gh-pages
          clean: false
        if: github.ref == 'refs/heads/main'
