# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
name: hoc-badge
'on':
  push:
    branches:
      - main
concurrency:
  group: hoc-badge-${{ github.ref }}
  cancel-in-progress: true
jobs:
  hoc-badge:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Build a HOC badge
        uses: MikhailEpatko/hits-of-code-badge@main
        with:
          output_dir: gh-pages
          filename: hoc-badge.svg
      - name: Release it into gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: gh-pages
          clean: false
        if: github.ref == 'refs/heads/main'
