# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
name: loc-badge
'on':
  push:
    branches:
      - main
      - master
concurrency:
  group: loc-badge-${{ github.ref }}
  cancel-in-progress: true
jobs:
  loc-badge:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Build a LOC badge
        uses: shadowmoose/GHA-LoC-Badge@1.0.0
        with:
          debug: true
          directory: .
          badge: target/loc-badge.svg
      - name: Release it into gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: target
          clean: false
        if: github.ref == 'refs/heads/main'
