# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
name: latex-release
env:
  DOCUMENT: document
'on':
  push:
    tags:
      - '*'
jobs:
  latex-release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ env.DOCUMENT }}.tex
          # yamllint disable-line rule:line-length
          post_compile: "mv ${{ env.DOCUMENT }}.pdf ${{ env.DOCUMENT }}-${{ github.ref_name }}.pdf"
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DOCUMENT }}-${{ github.ref_name }}
          path: ${{ env.DOCUMENT }}-${{ github.ref_name }}.pdf
      - name: Release PDF
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.DOCUMENT }}-${{ github.ref_name }}.pdf
          generate_release_notes: true
