# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
name: latex-release
'on':
  push:
    tags:
      - '[0-9]*.[0-9]*.[0-9]*'
defaults:
  run:
    shell: bash -xeuo pipefail {0}
permissions:
  contents: read
jobs:
  latex-build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Configure apt cache
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('**/apt-packages.txt') }}
          restore-keys: ${{ runner.os }}-apt-
      - name: Install dependencies
        run: |
          sudo apt-get update
          xargs -a apt-packages.txt sudo apt-get install \
            -y --no-install-recommends
      - name: Compile LaTeX document
        run: |
          [ -f Makefile ] && make clean && make
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: document
          path: ./*.pdf
  latex-release:
    runs-on: ubuntu-24.04
    needs: [latex-build]
    permissions:
      contents: write
    steps:
      - name: Download PDF
        uses: actions/download-artifact@v4
        with:
          name: document
          path: ./artifacts
      - name: Set release tag
        id: tag
        run: |
          # Detects which tag triggered the build
          echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
      - name: Release document
        # yamllint disable-line rule:line-length
        uses: softprops/action-gh-release@fbadcc90e88ecface60a0a0d123795b784ceb239
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          files: ./artifacts/*.pdf
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
