# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
name: latex-build
'on':
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
defaults:
  run:
    shell: bash -xeuo pipefail {0}
permissions:
  contents: read
env:
  DOCUMENT: document
jobs:
  latex-build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@25080975331dc4fc8e6f1af55788e00f84f51fff
        with:
          extra_system_packages: "inkscape plantuml"
          root_file: ${{ env.DOCUMENT }}.tex
          pre_compile: |
            tlmgr update --self
            tlmgr update --all
          # yamllint disable rule:line-length
          post_compile: |
            mv ${{ env.DOCUMENT }}.pdf ${{ env.DOCUMENT }}-${{ github.ref_name }}.pdf
          # yamllint enable rule:line-length
