# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
name: c-cpp-build-windows
'on':
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  c-cpp-build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          choco update
          choco install -y make gcc pkg-config
      - name: Configure and build
        run: |
          autogen.cmd
          configure
          make
      - name: Get properties from configure.ac
        id: props
        shell: bash
        # yamllint disable rule:line-length
        run: |
          name=$(sed -n 's/AC_INIT(\[\([^]]*\)\],.*/\1/p' configure.ac)
          echo "name=$name" >> $GITHUB_OUTPUT
          version=$(sed -n 's/AC_INIT(\[[^]]*\], \[\([^]]*\)\], \[[^]]*\])/\1/p' configure.ac)
          echo "version=$version" >> $GITHUB_OUTPUT
        # yamllint enable rule:line-length
      - name: Create source package
        run: |
          make dist
      - name: Create Windows binary package
        run: |
          make binary-dist
      - name: Prepare packages to distribution
        # yamllint disable rule:line-length
        run: |
          mkdir -p dist
          mv "${{ steps.props.outputs.name }}-${{ steps.props.outputs.version }}-bin.tar.gz" \
            "dist/${{ steps.props.outputs.name }}-${{ steps.props.outputs.version }}-windows.tar.gz"
        # yamllint enable rule:line-length
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-dist
          path: dist/*.zip
