# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
name: java-build-with-docker
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  java-build-with-docker:
    runs-on: ${{ matrix.os }}
    services:
      docker:
        image: docker:28.3.3
        options: --privileged
    strategy:
      matrix:
        os: [ubuntu-24.04]
        java: [11, 17, 21]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install -y maven
      - name: Setup Java SDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Configure Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          # yamllint disable-line rule:line-length
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - name: Build project
        run: |
          if [ -x "mvnw" ]; then
            MVN="./mvnw"
          else
            MVN=mvn
          fi
          if grep -q "<id>qulice</id>" pom.xml; then
            $MVN --errors --batch-mode clean install -Pqulice
          else
            $MVN --errors --batch-mode clean install
          fi
