# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: any-sonar
'on':
  push:
    branches:
      - main
      - master
permissions:
  contents: read
jobs:
  any-sonar:
    uses: fabriciofx/github-workflows/.github/workflows/any-sonar-template.yml@main
    with:
      working-directory: "."
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SN_TOKEN: ${{ secrets.SONAR_TOKEN }}
