# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
name: badge-hoc
'on':
  push:
    branches:
      - main
      - master
permissions:
  contents: write
jobs:
  badge-hoc:
    # yamllint disable-line rule:line-length
    uses: fabriciofx/github-workflows/.github/workflows/badge-hoc-template.yml@main
    with:
      output-dir: gh-pages
      filename: hoc-badge.svg
      branch: gh-pages
      folder: gh-pages
      clean: false
