# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
name: bash-format-template
'on':
  workflow_call:
defaults:
  run:
    shell: bash -xeuo pipefail {0}
permissions:
  contents: read
jobs:
  bash-format-template:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Check if code exists
        id: check
        uses: thebinaryfelix/check-file-existence-action@436223737a098725b8d10ab1950a03efba5e6fc6
        with:
          files: '**/*.sh'
      - name: Setup Python SDK
        if: steps.check.outputs.exists == 'true'
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install bashate
        run: pip install bashate
      - name: Check bash format
        run: |
          readarray -t files < <(find . -name "*.sh")
          [[ ${#files[@]} -eq 0 ]] && {
            echo "No '*.sh'. files found.";
            exit 0;
          }
          bashate -i E006,E003 "${files[@]}"
