# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
name: css-duplication
'on':
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
permissions:
  contents: read
jobs:
  css-duplication:
    # yamllint disable-line rule:line-length
    uses: fabriciofx/github-workflows/.github/workflows/css-duplication-template.yml@main
