# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
name: java-infer-template
'on':
  workflow_call:
defaults:
  run:
    shell: bash -xeuo pipefail {0}
permissions:
  contents: read
jobs:
  checkcode:
    runs-on: ubuntu-24.04
    outputs:
      proceed: ${{ steps.check.outputs.proceed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Check for code
        id: check
        run: |
          found=$(find . -maxdepth 1 -name "pom.xml")
          if [[ -n "${found}" ]]; then
            echo "proceed=true" >> "${GITHUB_OUTPUT}"
          else
            echo "Code not found. Stopping execution of the other jobs."
            echo "proceed=false" >> "${GITHUB_OUTPUT}"
          fi
  java-infer-template:
    runs-on: ubuntu-24.04
    needs: checkcode
    if: needs.checkcode.outputs.proceed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup Infer
        uses: srz-zumix/setup-infer@530856effeae228d1f3c8251c91ea8348d9480ee
      - name: Run infer
        run: |
          [[ -x "mvnw" ]] && mvn="./mvnw" || mvn="mvn"
          infer --version
          infer run --fail-on-issue --no-progress-bar -- "${mvn}" test
