# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
name: java-build-template
'on':
  workflow_call:
defaults:
  run:
    shell: bash -xeuo pipefail {0}
permissions:
  contents: read
jobs:
  checkcode:
    runs-on: ubuntu-24.04
    outputs:
      proceed: ${{ steps.check.outputs.proceed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Check for code
        id: check
        run: |
          found=$(find . -maxdepth 1 -name "pom.xml")
          if [[ -n "${found}" ]]; then
            echo "proceed=true" >> "${GITHUB_OUTPUT}"
          else
            echo "Code not found. Stopping execution of the other jobs."
            echo "proceed=false" >> "${GITHUB_OUTPUT}"
          fi
  java-linux-build-template:
    runs-on: ${{ matrix.os }}
    needs: checkcode
    if: needs.checkcode.outputs.proceed == 'true'
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        java: [11, 17, 21]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Configure APT cache
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('**/apt-packages.txt') }}
          restore-keys: ${{ runner.os }}-apt-
      - name: Install dependencies
        run: |
          if [[ -s apt-packages.txt ]]; then
            sudo apt-get update
            xargs sudo apt-get install -y \
              --no-install-recommends < apt-packages.txt
          fi
      - name: Setup Java SDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Configure Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          # yamllint disable-line rule:line-length
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - name: Build Maven project
        run: |
          [[ -x "mvnw" ]] && mvn="./mvnw" || mvn="mvn"
          args=(--errors --batch-mode install)
          profile=$(grep -q "<id>qulice</id>" pom.xml && echo "-Pqulice")
          [[ -n "${profile}" ]] && args+=("${profile}")
          ${mvn} "${args[@]}"
  java-macos-build-template:
    runs-on: ${{ matrix.os }}
    needs: checkcode
    if: needs.checkcode.outputs.proceed == 'true'
    strategy:
      matrix:
        os: [macos-14, macos-15]
        java: [11, 17, 21]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Configure Homebrew cache
        uses: actions/cache@v4
        with:
          path: /Users/runner/Library/Caches/Homebrew
          key: brew-cache-${{ runner.os }}-${{ hashFiles('**/Brewfile') }}
          restore-keys: brew-cache-${{ runner.os }}-
      - name: Install dependencies
        run: |
          if [[ -s brew-packages.txt ]]; then
            brew update
            xargs brew install < brew-packages.txt
          fi
      - name: Setup Java SDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Configure Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          # yamllint disable-line rule:line-length
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - name: Build Maven project
        run: |
          [[ -x "mvnw" ]] && mvn="./mvnw" || mvn="mvn"
          args=(--errors --batch-mode install)
          profile=$(grep -q "<id>qulice</id>" pom.xml && echo "-Pqulice")
          [[ -n "${profile}" ]] && args+=("${profile}")
          ${mvn} "${args[@]}"
  java-windows-build-template:
    runs-on: ${{ matrix.os }}
    needs: checkcode
    if: needs.checkcode.outputs.proceed == 'true'
    strategy:
      matrix:
        os: [windows-2022, windows-2025]
        java: [11, 17, 21]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Configure Chocolatey cache
        uses: actions/cache@v4
        with:
          path: |
            C:\ProgramData\chocolatey\cache
            C:\ProgramData\chocolatey\lib
          # yamllint disable-line rule:line-length
          key: choco-cache-${{ runner.os }}-${{ hashFiles('**/packages.config') }}
          restore-keys: choco-cache-${{ runner.os }}-
      - name: Install dependencies
        shell: cmd
        run: |
          @echo off
          setlocal enabledelayedexpansion
          if exist "choco-packages.txt" (
            for /f "usebackq delims=" %%P in ("choco-packages.txt") do (
              choco install %%P -y --ignore-checksums
            )
          )
      - name: Setup Java SDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Configure Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          # yamllint disable-line rule:line-length
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - name: Build Maven project
        shell: cmd
        # yamllint disable rule:line-length
        run: |
          @echo off
          for /f "delims=" %%i in ('findstr "<id>qulice</id>" pom.xml') do set "Q=1"
          if exist "mvnw.cmd" (set "M=mvnw.cmd") else (set "M=mvn")
          %M% --errors --batch-mode install %Q:~-2,-1%-Pqulice
        # yamllint enable rule:line-length
