# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
name: java-codecov
'on':
  push:
    branches:
      - main
      - master
defaults:
  run:
    shell: bash -xeuo pipefail {0}
permissions:
  contents: read
jobs:
  java-codecov:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup Java SDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Configure Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ubuntu-jdk-21-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ubuntu-jdk-21-maven-
      - name: Run tests
        # yamllint disable rule:line-length
        run: |
          # Choose maven embedded or system
          [ -x "mvnw" ] && MVN="./mvnw" || MVN="mvn"

          # If exist jacoco profile, execute using it
          PROFILE=$(grep -q "<id>jacoco</id>" pom.xml && echo "-Pjacoco" || echo "")
          ${MVN} --errors --batch-mode install "${PROFILE}"
        # yamllint enable rule:line-length
      - name: Checks code coverage
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
