# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: java-duplication-template
'on':
  workflow_call:
defaults:
  run:
    shell: bash -xeuo pipefail {0}
permissions:
  contents: read
jobs:
  java-duplication-template:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup Java SDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Download Simian
        run: |
          curl -sS -L --retry 3 -o /tmp/simian.jar \
            http://public.yegor256.com/simian.jar
      - name: Detect working directory
        id: detect
        run: |
          if [[ -d java ]]; then
            echo "dir=java" >> "${GITHUB_OUTPUT}"
          else
            echo "dir=." >> "${GITHUB_OUTPUT}"
          fi
      - name: Check Java code duplication
        working-directory: ${{ steps.detect.outputs.dir }}
        run: |
          java -jar /tmp/simian.jar -threshold=16 \
            -ignoreBlocks="simian-off:simian-on" "-excludes=**/it" "**/*.java"
