# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
name: python-tests-template
'on':
  workflow_call:
    secrets:
      SSL_SERVER_KEY:
        description: 'SSL Server key'
        required: true
      SSL_SERVER_CRT:
        description: 'SSL Server certicate'
        required: true
      SSL_CA_CRT:
        description: 'SSL certificate'
        required: true
defaults:
  run:
    shell: bash -xeuo pipefail {0}
permissions:
  contents: read
jobs:
  checkcode:
    runs-on: ubuntu-24.04
    outputs:
      proceed: ${{ steps.check.outputs.proceed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Check for code
        id: check
        run: |
          found=$(find . -maxdepth 1 -name "requirements.txt" -o -name "*.py")
          if [[ -n "${found}" ]]; then
            echo "proceed=true" >> "${GITHUB_OUTPUT}"
          else
            echo "Code not found. Stopping execution of the other jobs."
            echo "proceed=false" >> "${GITHUB_OUTPUT}"
          fi
  python-tests-template:
    runs-on: ubuntu-24.04
    needs: checkcode
    if: needs.checkcode.outputs.proceed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install venv and dependencies
        run: |
          if [[ -s Makefile ]]; then
            make install
          else
            python -m venv .venv
            . ./.venv/bin/activate
            pip install -r requirements.txt
          fi
      - name: Recreate certificates
        run: |
          if [[ -n "${{ secrets.SSL_SERVER_KEY }}" ]]; then
            mkdir certificates
            echo "${{ secrets.SSL_SERVER_KEY }}" | \
              base64 --decode > certificates/server.key
            echo "${{ secrets.SSL_SERVER_CRT }}" | \
              base64 --decode > certificates/server.crt
            echo "${{ secrets.SSL_CA_CRT }}" | \
              base64 --decode > certificates/ca.crt
          else
            echo "Set your SSL_SERVER_KEY in GitHub settings repository page."
          fi
      - name: Run tests
        run: |
          . ./.venv/bin/activate
          pytest
