# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
name: python-tests
'on':
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
defaults:
  run:
    shell: bash -xeuo pipefail {0}
permissions:
  contents: read
jobs:
  python-tests:
    name: python-tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install venv and requirements
        run: |
          if [ -s Makefile ]; then
            make install
          else
            python -m venv .venv
            . ./.venv/bin/activate
            pip install -r requirements.txt
          fi
      - name: Recreate certificates
        run: |
          if [ -n "${{ secrets.SSL_SERVER_KEY }}" ]; then
            mkdir certificates
            echo "${{ secrets.SSL_SERVER_KEY }}" | \
              base64 --decode > certificates/server.key
            echo "${{ secrets.SSL_SERVER_CRT }}" | \
              base64 --decode > certificates/server.crt
            echo "${{ secrets.SSL_CA_CRT }}" | \
              base64 --decode > certificates/ca.crt
          else
            echo "Set your SSL_SERVER_KEY in GitHub settings repository page."
          fi
      - name: Run tests
        run: |
          . ./.venv/bin/activate
          pytest
